services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boids_db
    ports:
      - "5433:5432"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6380:6379"
